### ISSUE TITLE
Link to the powerfolder is stale

### ISSUE THREAD

**Issue by mdperry** [eilslabs/PanCanQC#3]
I was trying to build the container on 2017-11-23 when I encountered this exception in the STDERR:
Resolving powerfolder.dkfz.de (powerfolder.dkfz.de)... 192.54.49.102
Connecting to powerfolder.dkfz.de (powerfolder.dkfz.de)|192.54.49.102|:443... connected.
HTTP request sent, awaiting response... 403 Download link expired
2017-11-23 21:46:12 ERROR 403: Download link expired.

Is this something that can be easily remedied (somehow/somewhere)?

Thanks,

-- Marc Perry

**Comment by buchhalt** [comment]
Hi Marc,

Thank you for the information. I just extended the link. Hopefully it will be valid now indefinitely.

Best,
Ivo

**Comment by mdperry** [comment]
Hi Ivo,

I tried building the container again from the GitHub repo, and I am getting the same error.  Next I tried pasting that URL (from the Dockerfile) into my browser and it also gave a 403 Error:
HTTP ERROR: 403

Download link expired

Something went wrong on 

/dl/fiJGFePRxoTVNk47XWbHYnXK/database_files.tar.gz 

It seems that you are not logged in or that you have
not sufficient permission to access this page or 
file please login again here:

Back to Login: https://powerfolder.dkfz.de

Did the URL stay the same (or does the new URL need to be updated in GitHub?)?

Thanks,

--Marc

**Comment by buchhalt** [comment]
Hi Marc,

Sorry about that. I removed the expiration date supposing that this sets it to an infinite date. Instead it just left the link expired. I now set the date to 2027. I hope it works now. Apologies for the inconveniences.

Best,
Ivo
